// src/react/Badge.tsx
import type { ComponentPropsWithRef } from "react";
import { badgeRecipe, type BadgeRecipeProps } from "../recipes/badge.js";

export type BadgeProps = ComponentPropsWithRef<"span"> & BadgeRecipeProps;

export function Badge({ tone, className, ...rest }: BadgeProps) {
  return <span className={badgeRecipe({ tone, className })} {...rest} />;
}

// src/svelte/Badge.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { badgeRecipe, type BadgeRecipeProps } from "../recipes/badge.js";

  let {
    tone,
    class: className,
    children,
    ...rest
  }: HTMLAttributes<HTMLSpanElement> &
    BadgeRecipeProps & { class?: string } = $props();
</script>

<span class={badgeRecipe({ tone, className })} {...rest}>
  {@render children?.()}
</span>
