// src/react/Divider.tsx
import type { ComponentPropsWithRef } from "react";
import { dividerRecipe, type DividerRecipeProps } from "../recipes/divider.js";

export type DividerProps = ComponentPropsWithRef<"div"> & DividerRecipeProps;

export function Divider({ orientation, className, ...rest }: DividerProps) {
  return (
    <div
      role="separator"
      aria-orientation={orientation ?? "horizontal"}
      className={dividerRecipe({ orientation, className })}
      {...rest}
    />
  );
}

// src/svelte/Divider.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import {
    dividerRecipe,
    type DividerRecipeProps,
  } from "../recipes/divider.js";

  let {
    orientation,
    class: className,
    ...rest
  }: HTMLAttributes<HTMLDivElement> &
    DividerRecipeProps & { class?: string } = $props();
</script>

<div
  role="separator"
  aria-orientation={orientation ?? "horizontal"}
  class={dividerRecipe({ orientation, className })}
  {...rest}
></div>
