// src/react/Panel.tsx
import type { ComponentPropsWithRef } from "react";
import { panelRecipe, type PanelRecipeProps } from "../recipes/panel.js";

export type PanelProps = ComponentPropsWithRef<"div"> & PanelRecipeProps;

export function Panel({
  tier,
  padding,
  interactive,
  className,
  ...rest
}: PanelProps) {
  return (
    <div
      className={panelRecipe({ tier, padding, interactive, className })}
      {...rest}
    />
  );
}

// src/svelte/Panel.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { panelRecipe, type PanelRecipeProps } from "../recipes/panel.js";

  let {
    tier,
    padding,
    interactive,
    class: className,
    children,
    ...rest
  }: HTMLAttributes<HTMLDivElement> &
    PanelRecipeProps & { class?: string } = $props();
</script>

<div class={panelRecipe({ tier, padding, interactive, className })} {...rest}>
  {@render children?.()}
</div>
