// src/svelte/Callout.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import {
    calloutRecipe,
    type CalloutRecipeProps,
  } from "../recipes/callout.js";

  let {
    tone,
    class: className,
    children,
    ...rest
  }: HTMLAttributes<HTMLDivElement> &
    CalloutRecipeProps & { class?: string } = $props();
</script>

<div role="note" class={calloutRecipe({ tone, className })} {...rest}>
  {@render children?.()}
</div>

// src/react/Callout.tsx
import type { ComponentPropsWithRef } from "react";
import { calloutRecipe, type CalloutRecipeProps } from "../recipes/callout.js";

export type CalloutProps = ComponentPropsWithRef<"div"> & CalloutRecipeProps;

export function Callout({ tone, className, ...rest }: CalloutProps) {
  return (
    <div role="note" className={calloutRecipe({ tone, className })} {...rest} />
  );
}
