// src/svelte/Link.svelte
<script lang="ts">
  import type { HTMLAnchorAttributes } from "svelte/elements";
  import { linkRecipe, type LinkRecipeProps } from "../recipes/link.js";

  let {
    subtle,
    external,
    class: className,
    children,
    ...rest
  }: HTMLAnchorAttributes &
    LinkRecipeProps & { class?: string; external?: boolean } = $props();

  const externalProps = $derived(
    external ? { target: "_blank", rel: "noreferrer" } : {},
  );
</script>

<a class={linkRecipe({ subtle, className })} {...externalProps} {...rest}>
  {@render children?.()}
</a>

// src/react/Link.tsx
import type { ComponentPropsWithRef } from "react";
import { linkRecipe, type LinkRecipeProps } from "../recipes/link.js";

export type LinkProps = ComponentPropsWithRef<"a"> &
  LinkRecipeProps & { external?: boolean };

export function Link({ subtle, external, className, ...rest }: LinkProps) {
  const externalProps = external ? { target: "_blank", rel: "noreferrer" } : {};
  return (
    <a
      className={linkRecipe({ subtle, className })}
      {...externalProps}
      {...rest}
    />
  );
}
