// src/svelte/Prose.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { proseRecipe } from "../recipes/prose.js";
  import { focusableWhenScrollable } from "../recipes/scrollable.js";
  import { remapCodeColors } from "../recipes/code-colors.js";

  let {
    html,
    class: className,
    ...rest
  }: Omit<HTMLAttributes<HTMLDivElement>, "children"> & {
    /**
     * Pre-rendered HTML from a trusted rendering pipeline (e.g. server-side
     * Typst HTML export). Injected verbatim so MathML and inline SVG survive —
     * never pass untrusted or user-supplied HTML.
     */
    html: string;
    class?: string;
  } = $props();

  let root = $state<HTMLDivElement>();
  $effect(() => {
    void html;
    if (root) {
      remapCodeColors(root);
      focusableWhenScrollable(root);
    }
  });
</script>

<div bind:this={root} class={proseRecipe({ className })} {...rest}>
  <!-- eslint-disable-next-line svelte/no-at-html-tags -- trusted pre-rendered pipeline output -->
  {@html html}
</div>

// src/react/Prose.tsx
import { useEffect, useRef, type ComponentPropsWithRef } from "react";
import { proseRecipe } from "../recipes/prose.js";
import { focusableWhenScrollable } from "../recipes/scrollable.js";
import { remapCodeColors } from "../recipes/code-colors.js";

export type ProseProps = Omit<
  ComponentPropsWithRef<"div">,
  "children" | "dangerouslySetInnerHTML"
> & {
  /**
   * Pre-rendered HTML from a trusted rendering pipeline (e.g. server-side
   * Typst HTML export). Injected verbatim so MathML and inline SVG survive —
   * never pass untrusted or user-supplied HTML.
   */
  html: string;
};

export function Prose({ html, className, ...rest }: ProseProps) {
  const ref = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!ref.current) return;
    remapCodeColors(ref.current);
    focusableWhenScrollable(ref.current);
  }, [html]);
  return (
    <div
      ref={ref}
      className={proseRecipe({ className })}
      dangerouslySetInnerHTML={{ __html: html }}
      {...rest}
    />
  );
}
