// src/svelte/Spinner.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import {
    spinnerRecipe,
    type SpinnerRecipeProps,
  } from "../recipes/spinner.js";

  let {
    size,
    label = "Loading",
    class: className,
    ...rest
  }: HTMLAttributes<HTMLSpanElement> &
    SpinnerRecipeProps & { label?: string; class?: string } = $props();
</script>

<span role="status" {...rest}>
  <span class={spinnerRecipe({ size, className })}></span>
  <span class="sr-only">{label}</span>
</span>

// src/react/Spinner.tsx
import type { ComponentPropsWithRef } from "react";
import { spinnerRecipe, type SpinnerRecipeProps } from "../recipes/spinner.js";

export type SpinnerProps = ComponentPropsWithRef<"span"> &
  SpinnerRecipeProps & { label?: string };

export function Spinner({
  size,
  label = "Loading",
  className,
  ...rest
}: SpinnerProps) {
  return (
    <span role="status" {...rest}>
      <span className={spinnerRecipe({ size, className })} />
      <span className="sr-only">{label}</span>
    </span>
  );
}
