// src/svelte/Switch.svelte
<script lang="ts">
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { switchRecipe, switchThumbRecipe } from "../recipes/switch.js";

  let {
    checked = $bindable(false),
    onCheckedChange,
    class: className,
    ...rest
  }: Omit<HTMLButtonAttributes, "onchange"> & {
    checked?: boolean;
    onCheckedChange?: (checked: boolean) => void;
    class?: string;
  } = $props();
</script>

<button
  type="button"
  role="switch"
  aria-checked={checked}
  onclick={() => {
    checked = !checked;
    onCheckedChange?.(checked);
  }}
  class={switchRecipe({ className })}
  {...rest}
>
  <span class={switchThumbRecipe()}></span>
</button>

// src/react/Switch.tsx
import type { ComponentPropsWithRef } from "react";
import { switchRecipe, switchThumbRecipe } from "../recipes/switch.js";

export type SwitchProps = Omit<ComponentPropsWithRef<"button">, "onChange"> & {
  checked: boolean;
  onCheckedChange?: (checked: boolean) => void;
};

export function Switch({
  checked,
  onCheckedChange,
  className,
  ...rest
}: SwitchProps) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      onClick={() => onCheckedChange?.(!checked)}
      className={switchRecipe({ className })}
      {...rest}
    >
      <span className={switchThumbRecipe()} />
    </button>
  );
}
