// src/demos/header.demo.svelte
<script lang="ts">
  import { Badge, Header, ThemeToggle } from "../svelte/index.js";
</script>

<div class="overflow-hidden rounded-md border border-line">
  <Header class="static">
    <span class="font-display font-semibold">Foundation UI</span>
    <nav class="flex items-center gap-4 text-sm text-ink-secondary">
      <span>Overview</span>
      <span>Tokens</span>
      <Badge tone="aurora">v1</Badge>
      <ThemeToggle />
    </nav>
  </Header>
  <div class="h-16 bg-surface"></div>
</div>

// src/demos/header.demo.tsx
import { Badge, Header, ThemeToggle } from "../react/index.js";

export default function HeaderDemo() {
  return (
    <div className="overflow-hidden rounded-md border border-line">
      <Header className="static">
        <span className="font-display font-semibold">Foundation UI</span>
        <nav className="flex items-center gap-4 text-sm text-ink-secondary">
          <span>Overview</span>
          <span>Tokens</span>
          <Badge tone="aurora">v1</Badge>
          <ThemeToggle />
        </nav>
      </Header>
      <div className="h-16 bg-surface" />
    </div>
  );
}
